# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cairo-gobject/all/cairo-gobject.rbi
#
# cairo-gobject-3.4.9

class Cairo::Context
  def self.gtype; end
end
class CairoGObject::Context < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::Device
  def self.gtype; end
end
class CairoGObject::Device < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::Pattern
  def self.gtype; end
end
class CairoGObject::Pattern < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::Surface
  def self.gtype; end
end
class CairoGObject::Surface < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::ScaledFont
  def self.gtype; end
end
class CairoGObject::ScaledFont < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::FontFace
  def self.gtype; end
end
class CairoGObject::FontFace < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::FontOptions
  def self.gtype; end
end
class CairoGObject::FontOptions < GLib::Boxed
  def self.try_convert(arg0); end
end
class Cairo::Region
  def self.gtype; end
end
class CairoGObject::Region < GLib::Boxed
  def self.try_convert(arg0); end
end
class CairoGObject::Status < GLib::Enum
end
class CairoGObject::Content < GLib::Enum
end
class CairoGObject::Operator < GLib::Enum
end
class CairoGObject::Antialias < GLib::Enum
end
class CairoGObject::FillRule < GLib::Enum
end
class CairoGObject::LineCap < GLib::Enum
end
class CairoGObject::LineJoin < GLib::Enum
end
class CairoGObject::TextClusterFlags < GLib::Enum
end
class CairoGObject::FontSlant < GLib::Enum
end
class CairoGObject::FontWeight < GLib::Enum
end
class CairoGObject::SubpixelOrder < GLib::Enum
end
class CairoGObject::HintStyle < GLib::Enum
end
class CairoGObject::HintMetrics < GLib::Enum
end
class CairoGObject::FontType < GLib::Enum
end
class CairoGObject::PathDataType < GLib::Enum
end
class CairoGObject::DeviceType < GLib::Enum
end
class CairoGObject::SurfaceType < GLib::Enum
end
class CairoGObject::Format < GLib::Enum
end
class CairoGObject::PatternType < GLib::Enum
end
class CairoGObject::Extend < GLib::Enum
end
class CairoGObject::Filter < GLib::Enum
end
class CairoGObject::RegionOverlap < GLib::Enum
end
module CairoGObject
end
