# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/mercenary/all/mercenary.rbi
#
# mercenary-0.4.0

module Mercenary
  def self.program(name); end
end
