name: Squib Unit Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1', '3.2', '3.3', '3.4', head]
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        # bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - run: ruby --version # explicitly show the ruby version
    - run: sudo apt-get update
    - run: sudo apt-get install libglib2.0-dev libgdk-pixbuf2.0-dev librsvg2-dev
    - run: bundle install
    - run: bundle exec rake
